Fix matrix bot
OAK-Foundation/faucet-bot pull request #2
Opened 2021-07-28 11:53 UTC by imstar15

2021-07-28 19:20 UTC, chrisli30 reviewed
咱们没有matrix，这个改动有实际测过吗？可以先这样

2021-07-29 01:11 UTC, chrisli30 requested changes

2021-07-29 01:11 UTC, chrisli30 commented on src/bot/index.js
> +    bot.sendHtmlMessage(roomId, `Sent ${sender} ${amount} OAKs.`);
这里需要使用我们自己的polkascan的URL

2021-07-29 01:11 UTC, chrisli30 commented on src/bot/index.js
> +    bot.sendHtmlMessage(roomId, `Sent ${sender} ${amount} OAKs.`);
polkascan的URL前缀应该是通过config传进来的

2021-07-29 07:57 UTC, imstar15 commented on src/bot/index.js
> +    bot.sendHtmlMessage(roomId, `Sent ${sender} ${amount} OAKs.`);
Fixed

2021-09-26 15:51 UTC, merged