Add discord bot
OAK-Foundation/faucet-bot pull request #3
Opened 2021-07-28 11:54 UTC by imstar15

2021-07-28 19:00 UTC, chrisli30 requested changes

2021-07-28 19:00 UTC, chrisli30 commented on src/bot/discord.js
> +  baseURL: process.env.BACKEND_URL,
程序开始的时候**分别检查**，BACKEND_URL和ACCESS_TOKEN，如果为空就报错

2021-07-28 19:00 UTC, chrisli30 commented on src/bot/discord.js
> +    msg.reply(`The faucet has ${balance/10**10} OAKs remaining.`, `The faucet has ${balance/10**10} OAKs remaining.`);
这不就是100吗，所有的100都直接使用一个常量，这种数字不要在程序里算

2021-07-28 19:00 UTC, chrisli30 commented on src/bot/discord.js
> +    let amount = 150;
我们是送100个OAK每次

2021-07-28 19:00 UTC, chrisli30 commented on src/bot/discord.js
> +    if (res.data === 'LIMIT') {
24小时之内只能给同一个地址送一次token，这里需要一个map，记录上次发送的address和时间，如果没到24小时就不发

这里是怎么实现的？，没看明白

2021-07-29 08:17 UTC, imstar15 commented on src/bot/discord.js
> +    if (res.data === 'LIMIT') {
在server代码里有以下实现，在数据库查询条件中加了时间的差值限制
```
async _query(item, span) {
    const timestamp = now();

    const query = {
      $and: [
        {item},
        {timestamp: { $gt: timestamp - span }},
      ],
    };

    return new Promise((resolve, reject) => {
      this._db.find(query, (err, docs) => {
        if (err) reject();
        resolve(docs.length);
      });
    });
  }
```

2021-07-29 08:18 UTC, imstar15 commented on src/bot/discord.js
> +    let amount = 150;
Fix

2021-07-29 08:18 UTC, imstar15 commented on src/bot/discord.js
> +    msg.reply(`The faucet has ${balance/10**10} OAKs remaining.`, `The faucet has ${balance/10**10} OAKs remaining.`);
Fixed

2021-07-29 08:18 UTC, imstar15 commented on src/bot/discord.js
> +  baseURL: process.env.BACKEND_URL,
Fixed

2022-01-07 09:28 UTC, closed without merging